# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: cargo build && cargo build --release # runs during prebuild
    command: |
      RUST_LOG=trace cargo run
      --bin dd-wrt-wol-api --
      --hosts 'name=desired-computer-name,mac_address=FF:FF:FF:FF:FF:FF,broadcast_ip=192.168.1.255'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - matklad.rust-analyzer
    - tamasfe.even-better-toml
    - serayuzgur.crates
